name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release - ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: dfrun
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: dfrun
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: dfrun.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.platform.target }}

      - name: Package Binary
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          tar -czf ../../../dfrun-${{ matrix.platform.target }}.tar.gz ${{ matrix.platform.binary_name }}
          cd -

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: dfrun-${{ matrix.platform.target }}.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dfrun-${{ matrix.platform.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
